pipeline {
    agent {label 'npm'}

    stages{
        stage('clone'){
            steps{
                git branch: 'main',
                url: 'https://github.com/rohi3369/devops-fullstack-app.git'
            }
        }
        stage('frontend'){
            steps{
                sh 'cd frontend'
                sh 'npm install'
                sh 'npm start'
            }
        }
        
        
    }

}