version: "3"
networks:
    2-tier:
        driver: bridge
services:
    frontend:
        build: 
            context: .
            dockerfile: ./devops-fullstack-app/frontend/Dockerfile
        container_name: EMS-frontend
        ports:
            - 3000:3000
        networks:
            - 2-tier
        environment:
            - API_URL=http://backend:8080

    backend:
        build: 
            context: .
            dockerfile: ./devops-fullstack-app/backend/Dockerfile
        container_name: EMS-backend
        ports:
            - 8080:8080
        networks:
            - 2-tier
        environment:
            - DB_HOST:EMS-postgres
            - DB_PORT:5432
            - DB_NAME:EMS
            - DB_USER:EMS
            - DB_PASSWORD:EMS
            - ALLOWED_ORIGINS:gorunmain.go
        depends_on:
            - db

    db:
        image: "postgres:9.6-alpine"
        container_name: EMS-postgres
        restart: always
        environment:
            - POSTGRES_DB:EMS
            - POSTGRES_USER:EMS
            - POSTGRES_PASSWORD:EMS
        networks:
            - 2-tier
        ports:
            - 5432:5432
